version: "3.8"

services:
  database_is:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: vasco1998
      POSTGRES_DB: inventory_system
